export const countryCodes = [
  { code: "+91", flag: "🇮🇳", name: "India" },
  { code: "+1", flag: "🇺🇸", name: "United States" },
  { code: "+1", flag: "🇨🇦", name: "Canada" },
  { code: "+44", flag: "🇬🇧", name: "United Kingdom" },
  { code: "+61", flag: "🇦🇺", name: "Australia" },
  { code: "+971", flag: "🇦🇪", name: "United Arab Emirates" },
  { code: "+65", flag: "🇸🇬", name: "Singapore" },
  { code: "+49", flag: "🇩🇪", name: "Germany" },
  { code: "+33", flag: "🇫🇷", name: "France" },
  { code: "+39", flag: "🇮🇹", name: "Italy" },
  { code: "+34", flag: "🇪🇸", name: "Spain" },
  { code: "+81", flag: "🇯🇵", name: "Japan" },
  { code: "+86", flag: "🇨🇳", name: "China" },
  { code: "+82", flag: "🇰🇷", name: "South Korea" },
  { code: "+7", flag: "🇷🇺", name: "Russia" },
  { code: "+55", flag: "🇧🇷", name: "Brazil" },
  { code: "+52", flag: "🇲🇽", name: "Mexico" },
  { code: "+27", flag: "🇿🇦", name: "South Africa" },
  { code: "+64", flag: "🇳🇿", name: "New Zealand" },
  { code: "+31", flag: "🇳🇱", name: "Netherlands" },
  { code: "+41", flag: "🇨🇭", name: "Switzerland" },
  { code: "+46", flag: "🇸🇪", name: "Sweden" },
  { code: "+47", flag: "🇳🇴", name: "Norway" },
  { code: "+358", flag: "🇫🇮", name: "Finland" },
  { code: "+45", flag: "🇩🇰", name: "Denmark" },
  { code: "+353", flag: "🇮🇪", name: "Ireland" },
  { code: "+32", flag: "🇧🇪", name: "Belgium" },
  { code: "+43", flag: "🇦🇹", name: "Austria" },
  { code: "+351", flag: "🇵🇹", name: "Portugal" },
  { code: "+30", flag: "🇬🇷", name: "Greece" },
  { code: "+90", flag: "🇹🇷", name: "Turkey" },
  { code: "+966", flag: "🇸🇦", name: "Saudi Arabia" },
  { code: "+974", flag: "🇶🇦", name: "Qatar" },
  { code: "+965", flag: "🇰🇼", name: "Kuwait" },
  { code: "+968", flag: "🇴🇲", name: "Oman" },
  { code: "+973", flag: "🇧🇭", name: "Bahrain" },
  { code: "+20", flag: "🇪🇬", name: "Egypt" },
  { code: "+62", flag: "🇮🇩", name: "Indonesia" },
  { code: "+60", flag: "🇲🇾", name: "Malaysia" },
  { code: "+66", flag: "🇹🇭", name: "Thailand" },
  { code: "+63", flag: "🇵🇭", name: "Philippines" },
  { code: "+84", flag: "🇻🇳", name: "Vietnam" },
  { code: "+92", flag: "🇵🇰", name: "Pakistan" },
  { code: "+880", flag: "🇧🇩", name: "Bangladesh" },
  { code: "+94", flag: "🇱🇰", name: "Sri Lanka" },
  { code: "+977", flag: "🇳🇵", name: "Nepal" },
  { code: "+54", flag: "🇦🇷", name: "Argentina" },
  { code: "+56", flag: "🇨🇱", name: "Chile" },
  { code: "+57", flag: "🇨🇴", name: "Colombia" },
  { code: "+51", flag: "🇵🇪", name: "Peru" },
  { code: "+58", flag: "🇻🇪", name: "Venezuela" },
  { code: "+254", flag: "🇰🇪", name: "Kenya" },
  { code: "+234", flag: "🇳🇬", name: "Nigeria" },
  { code: "+233", flag: "🇬🇭", name: "Ghana" },
  { code: "+972", flag: "🇮🇱", name: "Israel" },
  { code: "+380", flag: "🇺🇦", name: "Ukraine" },
  { code: "+48", flag: "🇵🇱", name: "Poland" },
  { code: "+420", flag: "🇨🇿", name: "Czech Republic" },
  { code: "+36", flag: "🇭🇺", name: "Hungary" },
  { code: "+40", flag: "🇷🇴", name: "Romania" },
  { code: "+359", flag: "🇧🇬", name: "Bulgaria" },
  { code: "+385", flag: "🇭🇷", name: "Croatia" },
  { code: "+356", flag: "🇲🇹", name: "Malta" },
  { code: "+357", flag: "🇨🇾", name: "Cyprus" },
  { code: "+352", flag: "🇱🇺", name: "Luxembourg" },
  { code: "+998", flag: "🇺🇿", name: "Uzbekistan" },
  { code: "+7", flag: "🇰🇿", name: "Kazakhstan" },
  { code: "+994", flag: "🇦🇿", name: "Azerbaijan" },
  { code: "+995", flag: "🇬🇪", name: "Georgia" },
  { code: "+374", flag: "🇦🇲", name: "Armenia" },
  { code: "+962", flag: "🇯🇴", name: "Jordan" },
  { code: "+961", flag: "🇱🇧", name: "Lebanon" },
  { code: "+964", flag: "🇮🇶", name: "Iraq" },
  { code: "+212", flag: "🇲🇦", name: "Morocco" },
  { code: "+213", flag: "🇩🇿", name: "Algeria" },
  { code: "+216", flag: "🇹🇳", name: "Tunisia" },
  { code: "+218", flag: "🇱🇾", name: "Libya" },
  { code: "+249", flag: "🇸🇩", name: "Sudan" },
  { code: "+251", flag: "🇪🇹", name: "Ethiopia" },
  { code: "+256", flag: "🇺🇬", name: "Uganda" },
  { code: "+255", flag: "🇹🇿", name: "Tanzania" },
  { code: "+260", flag: "🇿🇲", name: "Zambia" },
  { code: "+263", flag: "🇿🇼", name: "Zimbabwe" },
  { code: "+244", flag: "🇦🇴", name: "Angola" },
  { code: "+258", flag: "🇲🇿", name: "Mozambique" },
  { code: "+241", flag: "🇬🇦", name: "Gabon" },
  { code: "+237", flag: "🇨🇲", name: "Cameroon" },
  { code: "+221", flag: "🇸🇳", name: "Senegal" },
  { code: "+225", flag: "🇨🇮", name: "Ivory Coast" },
  { code: "+960", flag: "🇲🇻", name: "Maldives" },
  { code: "+95", flag: "🇲🇲", name: "Myanmar" },
  { code: "+855", flag: "🇰🇭", name: "Cambodia" },
  { code: "+856", flag: "🇱🇦", name: "Laos" },
  { code: "+673", flag: "🇧🇳", name: "Brunei" },
  { code: "+852", flag: "🇭🇰", name: "Hong Kong" },
  { code: "+886", flag: "🇹🇼", name: "Taiwan" },
  { code: "+853", flag: "🇲🇴", name: "Macau" },
  { code: "+976", flag: "🇲🇳", name: "Mongolia" },
  { code: "+679", flag: "🇫🇯", name: "Fiji" },
  { code: "+675", flag: "🇵🇬", name: "Papua New Guinea" }
];

export const issueBuckets: Record<string, string[]> = {
  'Numbers missing from my dashboard': [
    'Meter display is ON and showing numbers locally',
    'Meter display is ON but showing zero',
    'Meter display is completely blank or OFF',
    "I can't access the meter physically right now",
    "I'm not sure - I can only see the dashboard",
  ],
  'The readings look wrong or unusually high': [
    'Showing an absurdly large number',
    'Showing zero even though meter is running',
    "Dashboard number doesn't match meter display",
    "Water balance total doesn't add up",
    'Readings seem slightly high or low',
  ],
  'I need to correct or add some data': [
    'Read values directly from meter display',
    'Values from manual logbook',
    'Entered wrong value in portal and want correction',
    'Meter was replaced/serviced and data shifted',
    'Other',
  ],
  "A physical meter or sensor isn't working": [
    'Display is blank or not turning on',
    'Display shows numbers but portal shows nothing',
    'Readings are fluctuating randomly',
    'It keeps showing zero when water is flowing',
    'Visible physical damage on device',
  ],
  'I need something changed on my dashboard': [
    'Rename a meter or location',
    'Add/remove meter from water balance',
    'Change report or alert recipients',
    'Adjust alert limits (thresholds)',
    'Change layout/categories',
    'Something else',
  ],
  "My reports or alert emails aren't arriving": [
    'Daily/weekly report email not arriving',
    'Report arrived but has missing/NA values',
    'Alert emails are incorrect or excessive',
    'Alert emails have completely stopped',
    'PDF report has wrong branding/fields',
  ],
  "Something on the portal or app isn't working": [
    "Happens every time - consistently broken",
    'Happened a few times but not always',
    "Happened once - not sure if it'll repeat",
  ],
  'I need someone to visit my site': [
    'Install a new meter',
    'Calibrate/check an existing meter',
    'Replace a damaged/faulty meter',
    'Fix wiring or connectivity',
    "General check-up - not sure what's wrong",
  ],
};

export const doesIssueRequireUnits = (issueType: string): boolean => {
  const unitRequiredCategories = [
    'Numbers missing from my dashboard',
    'The readings look wrong or unusually high',
    'I need to correct or add some data',
    "A physical meter or sensor isn't working",
    'I need someone to visit my site'
  ];
  return unitRequiredCategories.includes(issueType);
};
